services:
  server:
    image: postgres:15
    container_name: server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: server
      POSTGRES_DB: server
    volumes:
      - server-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  server-data:
